### ISSUE TITLE
Implement one-stage designs

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#19]
Now that we have such a wonderfully general interface - why not allow optimizing simple one-stage designs as well? Should be a piece of cake - only two parameter n and c, right?

In practice, there will be a few locations in the code where I implicitly assumed TwoStageDesign - those might be a little bit of a headache but in principle should it should be straight-forward to do.

**Comment by MatheMax** [comment]
Hey, there is a pull request to this issue. 
Checks are still running ;)

**Comment by kkmann** [comment]
cf. #28
