### ISSUE TITLE
Implement group-sequential designs

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#20]
Well, exactly that. Defining GS as fixed n2, same as before - just that n2 is parameterized by a single parameter.

**Comment by MatheMax** [comment]
Am I correct when I think that I do not need a new class but only a new constructur here?

**Comment by MatheMax** [comment]
Should c2 be arbitrary? For runtime issues (we want this design to be the starting design in our optimization) maybe a combination test could be better (just one parameter)

**Comment by kkmann** [comment]
Hm, there are a few design choices here I guess. You could do without a new class by just tweaking the tunable_parameters etc. but I do not really like that ;)

Better: new class (maybe this is the time to introduce a new superclass but not right away) - but with a conversion method allowing to convert any GS design in a TwoStageDesgn.

New class means all the required methods will have to be reimplemented - and I think there will be a lot of copy paste. In that case we should defer the shared methods to a common superclass (second step!)

**Comment by kkmann** [comment]
> Should c2 be arbitrary? For runtime issues (we want this design to be the starting design in our optimization) maybe a combination test could be better (just one parameter)

Well, I feel that for a generic GS design it should be, right? Is there some kind of official definition of a GS Design?

Here it gets interesting and we could add further classes (but I'd start with the basics and keep some stuff or 0.2 ;)) Feel free to create a new milestone + issue for 0.2 though!

**Comment by MatheMax** [comment]
I opened a PR to this topic

**Comment by kkmann** [comment]
reference ? ;)
