### ISSUE TITLE
two-arm vs single arm

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#21]
haha, that's a fun one - I think we currently work with a single arm z test which is kinda boring. Extend this via the data distribution interface to two-stages (equal allocation for 0.1, everything else can come later ;))!

**Comment by MatheMax** [comment]
As long as we use equal allocation: What is the difference between one- and two-sample test?
When we allow to specify the variances, we should use Neyman allocation, as we know that this is optimal.
Or what do you think?

**Comment by kkmann** [comment]
there is just some factor 2 lurking somewhere again ;) we should sort this out properly.  Let's stick with one/two-arm for 0.1, everything else is a potential generalization not required for the first release!

**Comment by MatheMax** [comment]
As far as I see, we are currently working with sample sizes per group and a variance of 0.5. 
Hence, we are not using standardized effect sizes, you are right.
The variance could be included in the data distribution.
Is it more common to use total sample sizes or sample sizes per group?

**Comment by kkmann** [comment]
> As far as I see, we are currently working with sample sizes per group and a variance of 0.5.

I was hoping we were working with known but arbitrary variance and same n per group oO

> Hence, we are not using standardized effect sizes, you are right.

Why? In the normal case, the effect size is sqrt(n)*delta with unit variance , so delta IS the standardized effect size (one-arm case)

> The variance could be included in the data distribution.

Nope, since we work with z-values.

> Is it more common to use total sample sizes or sample sizes per group?

No idea ;) I guess overall is more consitent with the one-arm case?

**Comment by MatheMax** [comment]
I was confused yesterday... 
Of course we are working with z-values and therefore with standardized effect sizes (the word "standardized" should be missing in my text, but it does not matter in any case)

Anyway, what's the goal then? Multiplying by 2 is not difficult.
Or do you want an option "one/two-armed"?

**Comment by kkmann** [comment]
If it is not difficult, we could also do it ;) We should definitely support two arm designs by default since these are much more common. I guess the samples sizes of the designs should be per group to avoid having to impose a 'divisible by 2' constraint. Therefore we should make sure that everything works out for single arm / two-arm situations and provide ways of doing the necessary conversions.

**Comment by MatheMax** [comment]
resolved in #32
