### ISSUE TITLE
Choose only some parameters optimally

### ISSUE THREAD

**Issue by MatheMax** [kkmann/otsd#24]
I think we should make it possible to fix $n_1$ or even the complete first stage, as it was also mentioned in the paper's review. 
Is this straight-forward or do we even need a new class for this?

**Comment by kkmann** [comment]
unfortunately, GitHub Markdown does not support LaTeX ;) 

Yupp, would be nice. Doing this properly requires some thought though, right. Probably a good idea to do this properly from the beginning since #13 is essentially a special case, right?

**Comment by kkmann** [comment]
We do not need a new class (doesn't solve everything x))) ). 

Off the top of my head (not final!) I think one could extend tunable_parameters() to include options. these cannot be hard-coded though. So maybe you could specify a list of fields to convert to a numeric vector then?

    tunable_parameters(design, params = NULL)

would be the default return all
 
    tunable_parameters(design, params = c("n2", "c2")))

would leave the stage-one untouched. Challenge: update needs to be reworked to safely convert the result back to a design without much fuzz ;). Probably just add the same params argument there. 

I would only accept a PR with proper testing here ;)

**Comment by kkmann** [comment]
Again, good point + more or less prerequisite for resolving #13

**Comment by kkmann** [comment]
oh, and the suggested new `params` argument would probably have to be specified in the call to minimize(), right?
https://github.com/kkmann/otsd/blob/916e9e33c17293e180cd87ba6d26ca3c1295a459/R/minimize.R#L16-L22

**Comment by kkmann** [comment]
A suggestion on how to do this is implemented in  #29, different idea though: added new logical indicators for all slots which can be set to TRUE/FALSE and indicate whether or not that slow is a tunable parameter. This approach is pretty flexible but does not require huge changes elsewhere. Only tested for TwoStageDesigns so far (but if the others are proper subclasses it should work out of the box ;)).

**Comment by kkmann** [comment]
closing this as of #29, might need to reopen if we find further issues - still a bit rough around the edges ;)
