### ISSUE TITLE
Support of continuous prior

### ISSUE THREAD

**Issue by MatheMax** [kkmann/otsd#37]
Unfortunately, it turns out that the implemented integration by computing the posterior does not always work.

I think the problem is the following:
When computing the renormalizing constant, this constant can become very small.
This yields to quite large function values of the posterior density (on a small part of the support) and integrating the posterior does not necessarily return "1" anymore. 

For now, I see 3 possible ways:
1. Do not change anything and look for a suitable support for any problem
2. Compute the posterior by using Gaussian quadrature. This should work but will make the minimization very slow.
3. Start creating subclasses of "Continuous prior". This could at least help in the case of a normal prior when we know the posterior distribution.

@kkmann Do you have any suggestions?

**Comment by kkmann** [comment]
Hm, I personally don't see a problem with manually fixing sensible boundaries (can we detect that case and throw an informative error ?) Would be quick and totally practical (what's the difference between N(.1, .3)|[-1, 2] and N(.1, .3)[-5, 5] in practice ;) ??)

2) not an option I guess

3) maybe, open an issue for that but that is an nice to have add on for later and maybe not worth it (combinations explode if you allow other data distributions as well)

I'd go with 1) ;)

**Comment by MatheMax** [comment]
Alright, then I start writing the vignette ;)

Unfortunately we cannot detect the case because it can happen any time during optimization and then the error "pdf must integrate to one!" occurs.

**Comment by MatheMax** [comment]
I think we fixed this one with pr #35
