### ISSUE TITLE
Normal prior

### ISSUE THREAD

**Issue by MatheMax** [kkmann/otsd#38]
Since for a normal prior the posterior is known analytically, we could implement a subclass of ContinuousPrior and implement the normal distribution case.

**Comment by kkmann** [comment]
good idea in principle but this will get much too complicated if you want to support every combination of prior / data distribution. Don't think it is worth it. 
If we get to a point where we the current generic approach is unreasonable to maintain, I'd say suggest we'd only support conjugate priors for the respective data types and have an analytic posterior in all cases, right?

**Comment by MatheMax** [comment]
100% agree 👍
