### ISSUE TITLE
Vectorize functions

### ISSUE THREAD

**Issue by MatheMax** [kkmann/otsd#39]
Check what functions are used by stats::integrate and vectorize them all!

**Comment by kkmann** [comment]
I am reworking the tests for the continuous prior, the problem is not the definition of the continuous prior class but that we tacitly assumed that pdf / f are both vectorized (in expectation()). 
We need to check all occurrences of expectation() to make sure that is indeed fulfilled.

**Comment by kkmann** [comment]
https://github.com/kkmann/otsd/blob/4841af805556a068c02de5a00017189ab0252d40/R/SmoothnessN2.R#L54-L71

**Comment by kkmann** [comment]
https://github.com/kkmann/otsd/blob/e89ac5181cfe9a42e679943db6ce68e212ec436c/R/Scores.R#L193-L225

**Comment by kkmann** [comment]
I guess the scores part is critical 

https://github.com/kkmann/otsd/blob/c40797087fb0d99b64c355b9e070035673224df7/R/Scores.R#L212

this line assumes that evaluate and predictive_pdf are vectorized in x1 - @MatheMax can u check that?

**Comment by kkmann** [comment]
Okay, I think we can close this now as the root cause seems to be described in #43.
