### ISSUE TITLE
Resolve non-clean import of gaussquad dependency

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#4]
@MatheMax as of 83de4d2 `gaussquad` is imported via the Depends: field in DESCRIPTION. This is unclean since it attaches the gaussquad namespace.

gaussquad functions seem to be unusable without attaching the namespace though - complains about legendre.recurrence not being exported.

This should probably be fixed upstream in the gausquad package - is the maintainer still active? Do we have alternatives?

**Comment by MatheMax** [comment]
I found this implementation that does not need any other packages:
https://rdrr.io/cran/SMR/src/R/GaussLegendre.R

I tried some examples and it yields the same results as gaussquad.
What do you think about using it?

**Comment by kkmann** [comment]
looking good - nice and short. if it works well put it in util.R and remove all gaussquad references.
make sure to reference the source/autor were you got the code from ;)

**Comment by kkmann** [comment]
If this works , the only non-base-R dependency will be nloptr which is rock solid. That would be amazing!

**Comment by kkmann** [comment]
done as of  5e55a58. I also threw out the abstract 'Design' class (what is that ever going to be ;)) making our lives a lot easier for the current scope. GQDesign is now simply implemented as an additional constructor to TwoStageDesign which (as in your first implementation of GQDesign) supports arbitrary numerical integration schemes. 

+ I threw out all non-essential methods (e.g. n1(design) is now design@n1); sometimes considered bad style to expose slots directly to users, but hey - it's R and it saves us a few more lines of code.

still todo:

- [ ] proper referencing of where we got the GQ script from (currently only in source code
- [ ] implementing some tests

**Comment by kkmann** [comment]
#11 solves this - good job. We now only depend on nloptr (and methods) - excellent!
