### ISSUE TITLE
Implement simpler regularizer

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#49]
Following #47, we might get faster and more stable convergence by using suitable regularizers. 

Regularizing c2() is extremely difficult - at least I have no idea about how to chose a penalty parameter there. The scale is just too abstract. Regularizing n() is much easier. 
I would suggest trying to directly penalize the the integral over n2 on the continuation region (computed via Gauss quadrature) divided by the lenght of that interval. @MatheMax that should be easy to implement and could help with convergence without changing the shape of the solution as much as the smoothness term.

**Comment by MatheMax** [comment]
Isn't this just the 1-norm of n2?

**Comment by kkmann** [comment]
so what? just because it's simple doesn't mean it's useless or what is your point?

**Comment by kkmann** [comment]
implemented as of #51
