### ISSUE TITLE
improve generic integration rule

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd#8]
The generic evaluation currently ignores uncontinuous jumps at continuation area vs rest. should also integrate in three parts (also faster!). @MatheMax That's an easy one...

https://github.com/kkmann/otsd/blob/83de4d296e7a3057c450fb70710e42ccc7b90d79/R/Scores.R#L83-L106

**Comment by MatheMax** [comment]
This is just a copy/paste task, isn't it?

**Comment by kkmann** [comment]
Not quite, ideally you should have a look at #5 simultaneously. The way I see it .evaluate and evaluate should only differ by the way the mid section is computed, right? We should be fine using stats::integrate for the early stopping areas in both (with reduced default tolerance for speed, sth. like rel.tol=.001 or so).

**Comment by MatheMax** [comment]
Alright!

**Comment by kkmann** [comment]
you could even get rid of .evaluate and replace it with .compute_mid_section (btw, convention is to denote non-exported 'private' functions with .xyz in case u wondered...) eliminating the code redundency.

**Comment by MatheMax** [comment]
As far as I see the only existing class is TwoStageDesign
So, the specific rule will be applied in any case.
Where is my mistake? ;)

**Comment by kkmann** [comment]
it wont, you can call evaluate(specific=FALSE) to get the generic implementation (integrate mid section using stats::integrate) or use evaluate(specific=TRUE) [default] to switch to our manual implementation whcih is used during optimization.

I want to keep both (although we might be able to simplify here!) since you need to 'proof' that our crude integration rule is good enough ;)

**Comment by kkmann** [comment]
> Ok you're right ;-)
> But when only the mid section differs test_GaussLegendreIntegration already does the job because it tests the accuracy of the Gauss quadrature

the whole point of this slightly over-complicated implementation is to allow a choice between a well established standard numerical integration method with proper accuracy constraints (stats::integrate) and our custom/badly tested/heuristic/ alternative which we need for efficient optimization. We cannot prove that it works during optimization, but when reporting final scores of the optimal design we should evaluate the scores using established methods, right?

I'd be happy to simplify this a bit but we need to maintain tow options for evaluating the mid section of the integral.

Also, do you agree that the current way of evaluating the integral on the stopping region is just wrong?

**Comment by MatheMax** [comment]
Yes, it is wrong. I will think about a smart (and fast) alternative.

**Comment by kkmann** [comment]
well, why not simply use stats::integrate on the early stopping regions as in evaluate(), should work perfectly well ;). I'd start with copy/paste and if it works we can think about how to avoid the duplicate code ;)

**Comment by kkmann** [comment]
proposed fix on #15, please review and let me know what you think @MatheMax.

**Comment by kkmann** [comment]
should be  resolved as of #23  - hope we do not need to reopen this ;)
